#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width         5
bspc config window_gap           9

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config focused_border_color "#7899FA"
bspc config normal_border_color "#1f222b"

bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

xsetroot -cursor_name left_ptr

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# Keyboard layouts: TR + RU, Alt+Shift to toggle
setxkbmap -layout tr,ru -variant ,phonetic -option grp:lalt_lshift_toggle &

#AutoStart
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
dunst &
~/.config/polybar/launch.sh &
steam &
flameshot &
xrandr --output HDMI-0 --mode 1920x1080 --rate 180 &
nvidia-settings --load-config-only &
xinput --set-prop 9 "libinput Accel Speed" -1.0 &
feh --bg-scale Resimler/Wallpaper/1.jpg &
udiskie -t &
udisksctl mount -b /dev/sda1 &
udisksctl mount -b /dev/sdc1 &
bspc rule -a Ryujinx state=floating &
